version: "3"
services:
  etcd:
    image: qnib/plain-etcd
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
     - 8080:8080
    environment:
       ALLOW_HEALTHCHECK_OVERWRITE: "true"
       FISHERMAN_MIN_TASKS: "3"
       ETCD_CLUSTER_TOKEN: "etcd-1"
    deploy:
      replicas: 3
